version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.0
    - 5.0.2
    - 5.1.3
  - dependency-name: tslib
    versions:
    - 2.0.3
    - 2.1.0
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.165
  - dependency-name: less
    versions:
    - 3.12.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
